"""Add anomaly report tables

Revision ID: e4175dd6871a
Revises: d86266bb8d43
Create Date: 2026-08-29 01:43:00.825154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4175dd6871a'
down_revision: Union[str, Sequence[str], None] = 'd86266bb8d43'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('anomaly_reports',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('dataset_id', sa.String(), nullable=True),
    sa.Column('anomaly_start', sa.DateTime(), nullable=True),
    sa.Column('anomaly_end', sa.DateTime(), nullable=True),
    sa.Column('metric_name', sa.String(), nullable=True),
    sa.Column('severity', sa.Float(), nullable=True),
    sa.Column('recovered', sa.Boolean(), nullable=True),
    sa.Column('raw_decomposition', sa.JSON(), nullable=True),
    sa.Column('raw_rag', sa.JSON(), nullable=True),
    sa.Column('rejected_logs', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_anomaly_reports_id'), 'anomaly_reports', ['id'], unique=False)
    op.create_table('hypotheses',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('report_id', sa.String(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('evidence_strength', sa.String(), nullable=True),
    sa.Column('analyst_feedback', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['anomaly_reports.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hypotheses_id'), 'hypotheses', ['id'], unique=False)
    op.create_table('evidence',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('hypothesis_id', sa.String(), nullable=True),
    sa.Column('log_id', sa.String(), nullable=True),
    sa.Column('checkpoint', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('timestamp', sa.String(), nullable=True),
    sa.Column('details', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['hypothesis_id'], ['hypotheses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidence_id'), 'evidence', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evidence_id'), table_name='evidence')
    op.drop_table('evidence')
    op.drop_index(op.f('ix_hypotheses_id'), table_name='hypotheses')
    op.drop_table('hypotheses')
    op.drop_index(op.f('ix_anomaly_reports_id'), table_name='anomaly_reports')
    op.drop_table('anomaly_reports')
    # ### end Alembic commands ###
